-- ============================================================================
-- Aposentar o ledger paralelo e migrar o histórico para o financeiro
-- ----------------------------------------------------------------------------
-- 0023 made new orders raise a real receivable. This retires the ledger they
-- used to write instead, and brings the existing history across so the
-- Financeiro shows the store's whole life and not just what happened after the
-- bridge shipped.
--
--   1. shop_place_order stops writing public.transactions
--   2. every shop order already on file gets its receivable
--   3. every order that had settled becomes a receipt, dated from its payment
--
-- Step 1's function body is 0021's, byte for byte, minus the ledger INSERT —
-- generated by diffing rather than retyped, because re-emitting this function
-- from memory has silently dropped a later fix three times now (the ledger
-- close in 0019, the pre-discount shipping rule in 0021, party_id in 0021).
--
-- Idempotent. Nothing is deleted: public.transactions keeps its rows and stays
-- as the generic archetype table other verticals use — the shop simply stops
-- being one of its writers.
-- ============================================================================

-- 1. shop_place_order without the transactions write
CREATE OR REPLACE FUNCTION public.shop_place_order(
  p_tenant_id        uuid,
  p_items            jsonb,
  p_customer_id      uuid    DEFAULT NULL,
  p_customer_name    text    DEFAULT NULL,
  p_customer_email   text    DEFAULT NULL,
  p_currency         text    DEFAULT 'BRL',
  p_discount_code    text    DEFAULT NULL,
  p_shipping_total   numeric DEFAULT 0,
  p_notes            text    DEFAULT NULL,
  p_shipping_address jsonb   DEFAULT NULL,
  p_payment_method   text    DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_customer_id uuid          := NULL;
  v_order_id    uuid;
  v_lines       jsonb;
  v_line        record;
  v_product     public.plg_shop_products%ROWTYPE;
  v_disc        public.plg_shop_discounts%ROWTYPE;
  v_subtotal    numeric(12,2) := 0;
  v_discount    numeric(12,2) := 0;
  -- p_shipping_total is accepted for signature compatibility and DELIBERATELY
  -- ignored: the rate comes from the zones / shipping_settings. See 0015.
  v_shipping    numeric(12,2) := 0;
  v_total       numeric(12,2);
  v_applied     text          := NULL;
  v_email       text          := NULLIF(lower(trim(p_customer_email)), '');
  v_now         timestamptz   := now();
  v_owner       uuid;
  v_owner_email text;
  v_addr_id     uuid          := NULL;
  v_method      text          := NULLIF(lower(trim(p_payment_method)), '');
  v_free_shipping boolean     := false;
  v_postal      text          := NULLIF(regexp_replace(
                                   COALESCE(p_shipping_address->>'postal_code', ''),
                                   '\D', '', 'g'), '');
  v_quoted      numeric;
BEGIN
  IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'shop_place_order: no items' USING ERRCODE = '22023';
  END IF;

  IF v_method IS NOT NULL
     AND v_method NOT IN ('pix','credit_card','debit_card','boleto','cash','other') THEN
    RAISE EXCEPTION 'shop_place_order: unknown payment method %', v_method USING ERRCODE = '22023';
  END IF;

  -- Delivery coverage, checked before anything is written or decremented.
  -- Only enforced for a store that actually configured zones, so a merchant who
  -- has not set any keeps selling to every address exactly as before.
  IF EXISTS (SELECT 1 FROM public.shipping_zones
              WHERE tenant_id = p_tenant_id AND active) THEN
    IF v_postal IS NULL OR length(v_postal) <> 8 THEN
      RAISE EXCEPTION 'shop_place_order: postal code required for delivery'
        USING ERRCODE = '22023';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.shop_quote_shipping(p_tenant_id, v_postal, 0)) THEN
      RAISE EXCEPTION 'shop_place_order: delivery not available for postal code %', v_postal
        USING ERRCODE = '22023';
    END IF;
  END IF;

  IF p_customer_id IS NOT NULL THEN
    SELECT auth_user_id, lower(email) INTO v_owner, v_owner_email
      FROM public.plg_shop_customers
      WHERE id = p_customer_id AND tenant_id = p_tenant_id;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'shop_place_order: customer does not belong to this store'
        USING ERRCODE = '42501';
    END IF;
    IF v_owner IS NOT NULL AND v_owner IS DISTINCT FROM auth.uid() THEN
      RAISE EXCEPTION 'shop_place_order: customer belongs to another account'
        USING ERRCODE = '42501';
    END IF;
    IF v_owner IS NULL AND v_email IS NOT NULL AND v_owner_email IS DISTINCT FROM v_email THEN
      RAISE EXCEPTION 'shop_place_order: customer email mismatch'
        USING ERRCODE = '42501';
    END IF;

    v_customer_id := p_customer_id;
  END IF;

  IF v_customer_id IS NULL AND v_email IS NOT NULL THEN
    SELECT id INTO v_customer_id
      FROM public.plg_shop_customers
      WHERE tenant_id = p_tenant_id AND lower(email) = v_email
      LIMIT 1;
    IF v_customer_id IS NULL THEN
      INSERT INTO public.plg_shop_customers (tenant_id, first_name, last_name, email, auth_user_id)
      VALUES (p_tenant_id, COALESCE(NULLIF(trim(p_customer_name), ''), v_email), '', v_email, auth.uid())
      RETURNING id INTO v_customer_id;
    ELSIF auth.uid() IS NOT NULL THEN
      UPDATE public.plg_shop_customers SET auth_user_id = auth.uid()
        WHERE id = v_customer_id AND auth_user_id IS NULL;
    END IF;
  END IF;

  SELECT COALESCE(jsonb_agg(line), '[]'::jsonb) INTO v_lines
  FROM (
    SELECT jsonb_build_object(
             'product_id', (value->>'product_id')::uuid,
             'options_label', NULLIF(value->>'options_label', ''),
             'quantity', SUM(GREATEST(COALESCE((value->>'quantity')::int, 0), 0))::int
           ) AS line
    FROM jsonb_array_elements(p_items) AS value
    GROUP BY (value->>'product_id')::uuid, NULLIF(value->>'options_label', '')
    HAVING SUM(GREATEST(COALESCE((value->>'quantity')::int, 0), 0)) > 0
  ) grouped;

  IF jsonb_array_length(v_lines) = 0 THEN
    RAISE EXCEPTION 'shop_place_order: no items with a positive quantity' USING ERRCODE = '22023';
  END IF;

  FOR v_line IN
    SELECT (l->>'product_id')::uuid AS product_id,
           SUM((l->>'quantity')::int)::int AS quantity
      FROM jsonb_array_elements(v_lines) AS l
     GROUP BY 1
  LOOP
    SELECT * INTO v_product
      FROM public.plg_shop_products
      WHERE id = v_line.product_id AND tenant_id = p_tenant_id
      FOR UPDATE;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'shop_place_order: product % not found', v_line.product_id USING ERRCODE = '23503';
    END IF;
    IF v_product.status <> 'active' THEN
      RAISE EXCEPTION 'shop_place_order: product % is not active', v_product.id USING ERRCODE = '22023';
    END IF;
    IF v_product.inventory_count < v_line.quantity THEN
      RAISE EXCEPTION 'shop_place_order: insufficient stock for %', v_product.name USING ERRCODE = '23514';
    END IF;
    v_subtotal := v_subtotal + (v_product.price * v_line.quantity);
  END LOOP;

  v_subtotal := round(v_subtotal, 2);

  IF p_discount_code IS NOT NULL AND length(trim(p_discount_code)) > 0 THEN
    SELECT * INTO v_disc
      FROM public.plg_shop_discounts
      WHERE tenant_id = p_tenant_id AND lower(code) = lower(trim(p_discount_code))
      FOR UPDATE;
    IF FOUND
       AND v_disc.status = 'active'
       AND v_disc.starts_at <= v_now
       AND (v_disc.ends_at IS NULL OR v_disc.ends_at >= v_now)
       AND (v_disc.usage_limit IS NULL OR v_disc.times_used < v_disc.usage_limit)
       AND (NOT v_disc.once_per_customer OR v_customer_id IS NULL OR NOT EXISTS (
             SELECT 1 FROM public.plg_shop_orders o
             WHERE o.tenant_id = p_tenant_id
               AND o.customer_id = v_customer_id
               AND lower(o.discount_code) = lower(v_disc.code)))
    THEN
      v_applied := v_disc.code;
      IF v_disc.type = 'percentage' THEN
        v_discount := round(v_subtotal * v_disc.value / 100.0, 2);
      ELSIF v_disc.type = 'fixed_amount' THEN
        v_discount := LEAST(v_disc.value, v_subtotal);
      ELSIF v_disc.type = 'free_shipping' THEN
        v_free_shipping := true;
      END IF;
      UPDATE public.plg_shop_discounts SET times_used = times_used + 1 WHERE id = v_disc.id;
    END IF;
  END IF;

  v_discount := LEAST(GREATEST(v_discount, 0), v_subtotal);

  -- Shipping uses the PRE-discount subtotal, matching selectShipping() in the
  -- cart store. This is 0017's rule and it must survive every re-emission: an
  -- earlier draft of THIS migration copied 0015's post-discount line back in,
  -- which silently reinstated the bug where the cart promised free delivery and
  -- the order charged for it. The T8 regression caught it.
  -- A free_shipping discount still wins (it set v_free_shipping above).
  IF NOT v_free_shipping THEN
    v_quoted := public.shop_shipping_for(p_tenant_id, v_subtotal, v_postal);
    -- The coverage check above already refused an unserved address, so a NULL
    -- here can only mean "no zones and no shipping_settings row" — free.
    v_shipping := COALESCE(v_quoted, 0);
  END IF;

  v_total := GREATEST(round(v_subtotal - v_discount + v_shipping, 2), 0);

  -- Address book: only for an identified customer, and only when the payload
  -- carries the minimum a courier needs. Deduplicated so repeat orders to the
  -- same place reuse the row instead of stacking copies.
  IF v_customer_id IS NOT NULL
     AND p_shipping_address IS NOT NULL
     AND COALESCE(p_shipping_address->>'postal_code','') <> ''
     AND COALESCE(p_shipping_address->>'street','') <> '' THEN

    SELECT id INTO v_addr_id
      FROM public.addresses
     WHERE owner_type = 'shop_customer' AND owner_id = v_customer_id
       AND postal_code = p_shipping_address->>'postal_code'
       AND COALESCE(number, '') = COALESCE(p_shipping_address->>'number', '')
       AND COALESCE(complement, '') = COALESCE(p_shipping_address->>'complement', '')
     LIMIT 1;

    IF v_addr_id IS NULL THEN
      INSERT INTO public.addresses (
        tenant_id, owner_type, owner_id, label, recipient, phone, postal_code, street,
        number, complement, district, city, state, country, is_default
      ) VALUES (
        p_tenant_id, 'shop_customer', v_customer_id,
        NULLIF(p_shipping_address->>'label',''),
        NULLIF(p_shipping_address->>'recipient',''),
        NULLIF(p_shipping_address->>'phone',''),
        p_shipping_address->>'postal_code',
        p_shipping_address->>'street',
        NULLIF(p_shipping_address->>'number',''),
        NULLIF(p_shipping_address->>'complement',''),
        NULLIF(p_shipping_address->>'district',''),
        COALESCE(NULLIF(p_shipping_address->>'city',''), '—'),
        COALESCE(NULLIF(p_shipping_address->>'state',''), '—'),
        COALESCE(NULLIF(p_shipping_address->>'country',''), 'BR'),
        -- First address on file becomes the default.
        NOT EXISTS (SELECT 1 FROM public.addresses
                     WHERE owner_type = 'shop_customer' AND owner_id = v_customer_id)
      )
      RETURNING id INTO v_addr_id;
    END IF;
  END IF;

  INSERT INTO public.plg_shop_orders (
    tenant_id, status, financial_status, fulfillment_status, currency,
    subtotal, tax_total, discount_total, shipping_total, total,
    customer_id, customer_name, customer_email, discount_code, notes,
    shipping_address_id, shipping_address, payment_method_kind
  ) VALUES (
    p_tenant_id, 'open', 'pending', 'unfulfilled', COALESCE(p_currency, 'BRL'),
    v_subtotal, 0, v_discount, v_shipping, v_total,
    v_customer_id, NULLIF(trim(COALESCE(p_customer_name, '')), ''), v_email, v_applied, p_notes,
    v_addr_id, p_shipping_address, v_method
  )
  RETURNING id INTO v_order_id;

  FOR v_line IN
    SELECT (l->>'product_id')::uuid AS product_id,
           l->>'options_label'      AS options_label,
           (l->>'quantity')::int    AS quantity
      FROM jsonb_array_elements(v_lines) AS l
  LOOP
    SELECT * INTO v_product
      FROM public.plg_shop_products
      WHERE id = v_line.product_id AND tenant_id = p_tenant_id;

    INSERT INTO public.plg_shop_order_items (order_id, product_id, name, sku, quantity, unit_price, total, image_url)
    VALUES (
      v_order_id,
      v_product.id,
      CASE WHEN v_line.options_label IS NULL
        THEN v_product.name
        ELSE v_product.name || ' (' || v_line.options_label || ')' END,
      v_product.sku,
      v_line.quantity,
      v_product.price,
      round(v_product.price * v_line.quantity, 2),
      (SELECT url FROM public.plg_shop_product_images
         WHERE product_id = v_product.id ORDER BY is_primary DESC, sort_order ASC LIMIT 1)
    );
  END LOOP;

  UPDATE public.plg_shop_products p
     SET inventory_count = p.inventory_count - agg.quantity
    FROM (SELECT (l->>'product_id')::uuid AS product_id,
                 SUM((l->>'quantity')::int)::int AS quantity
            FROM jsonb_array_elements(v_lines) AS l
           GROUP BY 1) agg
   WHERE p.id = agg.product_id;

  -- No ledger row here any more. The receivable is raised by the
  -- plg_shop_orders_raise_receivable trigger (0023), which calls the financial
  -- plugin's own invoicing function — so the money lives in
  -- plg_financial_movements, where the Financeiro screens actually read it,
  -- instead of in public.transactions, which nothing reads.

  RETURN v_order_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.shop_place_order(uuid, jsonb, uuid, text, text, text, text, numeric, text, jsonb, text)
  TO anon, authenticated;


-- ----------------------------------------------------------------------------
-- 2a. Remember which orders were already settled — BEFORE raising any bill.
--
-- Order matters and getting it wrong destroys data: the moment a bill is
-- inserted, 0023's trigger re-derives financial_status from the receivable,
-- which at that instant has no receipts, so every historically 'paid' order is
-- rewritten to 'pending' and its paid_at cleared. Reading the paid set
-- afterwards therefore finds nothing. It is snapshotted first.
-- ----------------------------------------------------------------------------
-- NOT `ON COMMIT DROP`: this file is executed statement-by-statement, outside
-- any transaction block (psql -f, and the Management API's query endpoint
-- alike), so ON COMMIT DROP destroys the snapshot the instant it is committed —
-- the very next statement. Step 3 then joined a table that no longer existed
-- and the whole historical receipt backfill never ran. Session-scoped instead,
-- dropped explicitly once step 3 is done.
DROP TABLE IF EXISTS _shop_paid_before_backfill;
CREATE TEMP TABLE _shop_paid_before_backfill AS
SELECT s.id AS order_id,
       COALESCE(
         (SELECT max(t.transacted_at)::date
            FROM public.transactions t
           WHERE t.kind = 'shop_payment' AND t.status = 'paid'
             AND (t.order_id = s.id OR t.metadata->>'shop_order_id' = s.id::text)),
         s.paid_at::date,
         s.created_at::date
       ) AS paid_on
  FROM public.plg_shop_orders s
 WHERE s.financial_status = 'paid';

-- ----------------------------------------------------------------------------
-- 2b. Raise the receivable for every shop order already on file
--
-- One statement per order rather than a set-based INSERT because
-- fn_invoice_from_order_internal owns the numbering (next_sequence) and the
-- idempotency check. Reusing it means the backfilled invoices are
-- indistinguishable from the ones raised live — which is the point.
-- ----------------------------------------------------------------------------
DO $$
DECLARE r record; v_done int := 0; v_skipped int := 0;
BEGIN
  FOR r IN
    SELECT o.id
      FROM public.orders o
      JOIN public.plg_shop_orders s ON s.id = o.id
     WHERE o.kind = 'shop'
       AND NOT EXISTS (
         SELECT 1 FROM public.plg_financial_movements m
          WHERE m.invoice_id = o.id AND m.movement_kind = 'bill')
     ORDER BY o.created_at
  LOOP
    BEGIN
      PERFORM public.fn_invoice_from_order_internal(r.id, current_date, NULL, 1, 'credit');
      v_done := v_done + 1;
    EXCEPTION WHEN OTHERS THEN
      -- One malformed historical order must not abort the migration for the
      -- other nine hundred.
      v_skipped := v_skipped + 1;
      RAISE WARNING 'backfill: pedido % ignorado (%)', r.id, SQLERRM;
    END;
  END LOOP;
  RAISE NOTICE 'contas a receber criadas: %, ignoradas: %', v_done, v_skipped;
END $$;

-- ----------------------------------------------------------------------------
-- 3. Money that had already arrived becomes a receipt
--
-- The old world recorded settlement in two places that could disagree:
-- transactions.status='paid' and plg_shop_orders.financial_status='paid'. The
-- order is the one the merchant saw, so it is the one trusted here.
-- ----------------------------------------------------------------------------
INSERT INTO public.plg_financial_movements (
  tenant_id, invoice_id, direction, movement_kind, amount, paid_amount,
  status, due_date, payment_date, installment_number, notes, metadata
)
SELECT
  b.tenant_id, b.invoice_id, b.direction, 'payment', b.amount, b.amount,
  'paid', b.due_date,
  s.paid_on,
  b.installment_number,
  'Recebimento migrado do histórico da loja',
  jsonb_build_object('backfilledFromShopOrder', s.order_id)
  FROM public.plg_financial_movements b
  JOIN _shop_paid_before_backfill s ON s.order_id = b.invoice_id
 WHERE b.movement_kind = 'bill'
   AND COALESCE(b.paid_amount, 0) = 0
   AND NOT EXISTS (
     SELECT 1 FROM public.plg_financial_movements p
      WHERE p.invoice_id = b.invoice_id
        AND p.movement_kind = 'payment'
        AND p.installment_number IS NOT DISTINCT FROM b.installment_number);

UPDATE public.plg_financial_movements b
   SET paid_amount = b.amount, status = 'paid',
       payment_date = COALESCE(b.payment_date, s.paid_on), updated_at = now()
  FROM _shop_paid_before_backfill s
 WHERE s.order_id = b.invoice_id
   AND b.movement_kind = 'bill'
   AND COALESCE(b.paid_amount, 0) = 0;

-- The snapshot has done its job. Dropped here rather than left to session end so
-- a replay in the same session rebuilds it from current state.
DROP TABLE IF EXISTS _shop_paid_before_backfill;

-- The status of every backfilled order now follows from its receipts. Re-derived
-- explicitly so a historical order whose enum disagreed with its money is
-- corrected here rather than at some random future write.
DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT DISTINCT invoice_id FROM public.plg_financial_movements
            WHERE movement_kind = 'bill' AND invoice_id IS NOT NULL
  LOOP
    PERFORM public.refresh_shop_financial_status(r.invoice_id);
  END LOOP;
END $$;
