import { defineConfig } from 'tsup'
export default defineConfig({
  entry: {
    index: 'src/index.ts',
    ui: 'src/ui.ts',
    catalog: 'src/catalog.ts',
    shop: 'src/shop.ts',
  },
  format: ['esm', 'cjs'],
  dts: false,
  splitting: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  external: [
    'react',
    'react-dom',
    'zustand',
    'lucide-react',
    '@fayz-ai/core',
    '@fayz-ai/auth',
    '@fayz-ai/plugin-auth',
    '@fayz-ai/sdk',
    '@fayz-ai/sdk/shop',
    '@fayz-ai/shop',
    '@fayz-ai/shop/runtime',
    '@fayz-ai/shop/mock',
    '@fayz-ai/shop/catalog',
    '@fayz-ai/ui',
  ],
})
