// Utilities
export { cn } from './utils/cn'

// Primitives
export {
  Button,
  buttonVariants,
  type ButtonProps,
  Input,
  type InputProps,
  Badge,
  badgeVariants,
  type BadgeProps,
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardDescription,
  CardContent,
  Modal,
  ModalPortal,
  ModalOverlay,
  ModalClose,
  ModalTrigger,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  ModalTitle,
  ModalDescription,
  type ModalSize,
  Dropdown,
  DropdownTrigger,
  DropdownContent,
  DropdownItem,
  DropdownCheckboxItem,
  DropdownRadioItem,
  DropdownLabel,
  DropdownSeparator,
  DropdownShortcut,
  DropdownGroup,
  DropdownPortal,
  DropdownSub,
  DropdownSubContent,
  DropdownSubTrigger,
  DropdownRadioGroup,
  DataTable,
  type DataTableProps,
  Checkbox,
  type CheckboxColor,
  type CheckboxProps,
  Sheet,
  SheetPortal,
  SheetOverlay,
  SheetTrigger,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetBody,
  SheetFooter,
  SheetTitle,
  SheetDescription,
  Select,
  SelectGroup,
  SelectValue,
  SelectTrigger,
  SelectContent,
  SelectLabel,
  SelectItem,
  SelectSeparator,
  SelectScrollUpButton,
  SelectScrollDownButton,
  ToastProvider,
  toast,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Separator,
  Breadcrumb,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider,
  TimePicker,
  Skeleton,
  TableSkeleton,
  ListView,
  DatePicker,
  SearchSelect,
  type SearchSelectOption,
  type SearchSelectProps,
  CurrencyInput,
  ConfirmDialog,
  Popover,
  PopoverTrigger,
  PopoverContent,
} from './primitives'

// Layout
export {
  AppShell,
  type AppShellProps,
  type AppShellUser,
  Sidebar,
  type SidebarProps,
  type SidebarUser,
  type NavigationItem,
  ICON_MAP,
  Topbar,
  type TopbarProps,
  ModulePage,
  SubpageHeader,
  type ModulePageProps,
  type ModuleNavItem,
  type SubpageHeaderProps,
} from './layout'

// Stores
export {
  useLayoutStore,
  useThemeStore,
  lightTheme,
  darkTheme,
  type ThemeTokens,
  type SemanticColors,
  type UIPerceptionTokens,
  type CreateThemeOptions,
} from './stores'

// Theme
export {
  ThemeProvider,
  useTheme,
  createTheme,
  createFayzTheme,
  fayzThemePresets,
  type ThemeProviderProps,
  type FayzThemePresetId,
} from './theme'

// Avatar (used by the admin shell: TeamTab, UserProfile)
export { Avatar, AvatarImage, AvatarFallback } from './primitives/Avatar'
