// Utilities
export { cn } from './utils/cn'

// Primitives
export {
  Button,
  buttonVariants,
  type ButtonProps,
  Input,
  type InputProps,
  Badge,
  badgeVariants,
  type BadgeProps,
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardDescription,
  CardContent,
  Modal,
  ModalPortal,
  ModalOverlay,
  ModalClose,
  ModalTrigger,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  ModalTitle,
  ModalDescription,
  type ModalSize,
  Dropdown,
  DropdownTrigger,
  DropdownContent,
  DropdownItem,
  DropdownCheckboxItem,
  DropdownRadioItem,
  DropdownLabel,
  DropdownSeparator,
  DropdownShortcut,
  DropdownGroup,
  DropdownPortal,
  DropdownSub,
  DropdownSubContent,
  DropdownSubTrigger,
  DropdownRadioGroup,
  DataTable,
  type DataTableProps,
  Checkbox,
  type CheckboxColor,
  type CheckboxProps,
  Sheet,
  SheetPortal,
  SheetOverlay,
  SheetTrigger,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetBody,
  SheetFooter,
  SheetTitle,
  SheetDescription,
  Select,
  SelectGroup,
  SelectValue,
  SelectTrigger,
  SelectContent,
  SelectLabel,
  SelectItem,
  SelectSeparator,
  SelectScrollUpButton,
  SelectScrollDownButton,
  ToastProvider,
  toast,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Separator,
  Breadcrumb,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider,
  TimePicker,
  Skeleton,
  TableSkeleton,
  ListView,
  DatePicker,
  SearchSelect,
  type SearchSelectOption,
  type SearchSelectProps,
  CurrencyInput,
  ConfirmDialog,
  Popover,
  PopoverTrigger,
  PopoverContent,
  SegmentedControl,
  type SegmentedControlProps,
  type SegmentedOption,
  Markdown,
  renderMarkdown,
  type MarkdownProps,
  MarkdownEditor,
  type MarkdownEditorProps,
  SearchCombobox,
  type ComboboxOption,
} from './primitives'

// Layout
export {
  AppShell,
  type AppShellProps,
  type AppShellUser,
  type BottomNavItem,
  type BottomNavRouteItem,
  type BottomNavActionItem,
  type MobileHeaderVariant,
  Sidebar,
  type SidebarProps,
  type SidebarUser,
  type NavigationItem,
  ICON_MAP,
  Topbar,
  type TopbarProps,
  ModulePage,
  SubpageHeader,
  ContentSplit,
  ContentSplitTrigger,
  ModuleLayoutProvider,
  useModuleLayout,
  PageHeaderActions,
  BackStyleProvider,
  useBackStyle,
  SaveBar,
  SaveBarProvider,
  useSaveBar,
  useBackHandler,
  type SaveBarRegistration,
  useModuleHeaderSlot,
  useModuleHeaderActionsSlot,
  PageTransition,
  NavTransitionProvider,
  useNavTransition,
  type NavTransition,
  type ModulePageProps,
  type ModuleNavItem,
  type ModuleNavVariant,
  type SubpageHeaderProps,
  type ContentSplitProps,
  type ContentSplitTriggerProps,
  type BackButtonStyle,
} from './layout'

// Stores
export {
  useLayoutStore,
  useThemeStore,
  lightTheme,
  darkTheme,
  type ThemeTokens,
  type SemanticColors,
  type UIPerceptionTokens,
  type CreateThemeOptions,
} from './stores'

// Theme
export {
  ThemeProvider,
  useTheme,
  createTheme,
  createFayzTheme,
  fayzThemePresets,
  type ThemeProviderProps,
  type FayzThemePresetId,
} from './theme'

// Avatar (used by the admin shell: TeamTab, UserProfile)
export { Avatar, AvatarImage, AvatarFallback } from './primitives/Avatar'

// Dashboard widget kit
export {
  DashboardCanvas,
  WidgetGrid,
  DashboardNavigateProvider,
  useDashboardNavigate,
  type DashboardCanvasProps,
  resolveDashboardLayout,
  type LaidOutWidget,
  useDashboardPreferences,
  type DashboardPreferencesState,
  DashboardCustomizeMenu,
  type DashboardCustomizeMenuProps,
  DashboardGrid,
  type DashboardGridItem,
  type DashboardGridProps,
  GoldCard,
  type GoldCardProps,
  DashboardRangeProvider,
  DashboardRangeControl,
  useDashboardRange,
  DEFAULT_RANGE_OPTIONS,
  type DashboardRange,
  type DashboardRangeProviderProps,
  type DashboardRangeOptions,
  KpiCard,
  formatKpiValue,
  type KpiCardProps,
  ChartWidget,
  type ChartWidgetProps,
  TableWidget,
  type TableWidgetProps,
  OnboardingWidget,
  type OnboardingStepInput,
  type OnboardingWidgetProps,
  renderIcon,
  defineKpiWidget,
  defineChartWidget,
  defineTableWidget,
  defineOnboardingWidget,
  defineCustomWidget,
  type DefineWidgetInput,
  type KpiFormat,
  type KpiTrend,
  type KpiValue,
  type KpiCurrency,
  type IconRef,
  type ChartType,
  type ChartSeries,
} from './dashboard'
