import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { resolveFayzPackageDependencies } from '../lib/package-versions.js'

type Kind = 'storefront' | 'admin' | 'member'

const KINDS: Kind[] = ['storefront', 'admin', 'member']

function write(root: string, rel: string, content: string): void {
  const full = resolve(root, rel)
  mkdirSync(dirname(full), { recursive: true })
  writeFileSync(full, content)
}

// ---------------------------------------------------------------------------
// Per-kind template descriptor — the single source the generators read so a new
// surface type is one table entry, not a fork of every function.
// ---------------------------------------------------------------------------
interface KindTemplate {
  /** Extra app-owned deps beyond @fayz-ai/sdk + react. */
  extraDeps: string[]
  manifest(name: string): unknown
  /** Body of src/plugins.generated.ts. */
  pluginsGenerated(): string
  /** Surface name to mount (renderApp surface). */
  surface: string
  note?: string
}

const TEMPLATES: Record<Kind, KindTemplate> = {
  storefront: {
    extraDeps: [],
    surface: 'storefront',
    manifest: (name) => ({
      manifestVersion: 2,
      id: name,
      name,
      backend: { provider: 'mock' },
      locale: { default: 'pt-BR', supported: ['pt-BR'], currency: 'BRL' },
      theme: { name: 'default' },
      surfaces: {
        storefront: {
          scaffold: 'storefront',
          options: {
            announcement: `BEM-VINDO À ${name.toUpperCase()}`,
            home: {
              sections: [
                { type: 'hero', variant: 'banner', slides: [{ title: name, subtitle: 'Sua nova loja' }] },
                { type: 'products', title: 'Destaques', filter: 'all', limit: 8 },
                { type: 'newsletter', title: 'Novidades no seu e-mail' },
              ],
            },
            footer: { about: `${name} — feito com Fayz.` },
          },
        },
      },
    }),
    pluginsGenerated: () =>
      `// Generated by 'fayz create'. Maps manifest plugin ids → platform-bundled plugin factories.
// This storefront app uses no plugins.
export {}
`,
  },

  admin: {
    extraDeps: [],
    surface: 'admin',
    manifest: (name) => ({
      manifestVersion: 2,
      id: name,
      name,
      backend: { provider: 'mock' },
      locale: { default: 'pt-BR', supported: ['pt-BR', 'en'], currency: 'BRL' },
      theme: { brand: 'violet' },
      surfaces: {
        admin: { scaffold: 'admin', plugins: [{ id: 'dashboard' }], pages: [] },
      },
    }),
    pluginsGenerated: () =>
      `// Generated by 'fayz create'. Maps manifest plugin ids → platform-bundled plugin factories.
// Dashboard is supplied by the Fayz app-runtime bundle until Beauty proves the
// public package boundary.
export {}
`,
  },

  member: {
    // The member scaffold + courses domain are platform-bundled until this
    // surface is proven enough to expose as public packages.
    extraDeps: [],
    surface: 'member',
    manifest: (name) => ({
      manifestVersion: 2,
      id: name,
      name,
      backend: { provider: 'mock' },
      locale: { default: 'pt-BR', supported: ['pt-BR', 'en'] },
      surfaces: {
        member: {
          scaffold: 'member',
          options: { accent: '#10b981', autoEnroll: true },
        },
      },
    }),
    pluginsGenerated: () =>
      `// Generated by 'fayz create'. Member scaffold/provider wiring is supplied
// by the Fayz app-runtime bundle until this surface is proven as public API.
export {}
`,
    note: 'The member portal seeds a mock course catalog; any login grants access (autoEnroll). Replace the provider with a Supabase-backed one for production.',
  },
}

function packageJson(name: string, kind: Kind): string {
  const deps: Record<string, string> = {
    ...resolveFayzPackageDependencies('stable'),
    react: '^18.3.0',
    'react-dom': '^18.3.0',
  }
  for (const dep of TEMPLATES[kind].extraDeps) deps[dep] = 'latest'
  return (
    JSON.stringify(
      {
        name,
        private: true,
        version: '0.1.0',
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: deps,
        devDependencies: {
          '@vitejs/plugin-react': '^4.3.0',
          typescript: '^5.5.0',
          vite: '^5.4.0',
        },
      },
      null,
      2,
    ) + '\n'
  )
}

function manifestJson(name: string, kind: Kind): string {
  return JSON.stringify(TEMPLATES[kind].manifest(name), null, 2) + '\n'
}

function mainTsx(surface: string): string {
  return `import React from 'react'
import { createRoot } from 'react-dom/client'
import { renderApp } from './lib/fayz-runtime'
import './styles.css'
import './plugins.generated' // registers plugin factories + scaffolds + providers
import './registry' // app-local custom blocks / components / overrides
import manifest from '../app.manifest.json'

createRoot(document.getElementById('root')!).render(
  <React.StrictMode>{renderApp(manifest as never, { surface: '${surface}' })}</React.StrictMode>,
)
`
}

function fayzRuntimeTs(): string {
  return `import React from 'react'

export function renderApp(manifest: { name?: string }, options?: { surface?: string }) {
  const surface = options?.surface ?? 'admin'

  return React.createElement(
    'main',
    { style: { fontFamily: 'Inter, system-ui, sans-serif', padding: 24 } },
    React.createElement('h1', null, manifest.name ?? 'Fayz App'),
    React.createElement(
      'p',
      null,
      'Fayz app-runtime is bundled by the platform until the Beauty manifest proof promotes it to public package API.',
    ),
    React.createElement('pre', null, JSON.stringify({ surface }, null, 2)),
  )
}
`
}

function registryTsx(): string {
  return `// App-local custom code (customization ladder levels 5–7). Register custom
// blocks, pages, components and metric overrides here; reference them from
// app.manifest.json by their 'custom:' id.
//
//   import { registerBlock } from './lib/fayz-runtime'
//   registerBlock('custom:my-block', MyBlock)
export {}
`
}

function viteConfig(): string {
  return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  // Generated apps consume @fayz-ai/sdk from npm. App-runtime is bundled by
  // Fayz until the Beauty manifest proof promotes it to public package API.
})
`
}

function tsconfig(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          lib: ['ES2020', 'DOM', 'DOM.Iterable'],
          module: 'ESNext',
          moduleResolution: 'bundler',
          jsx: 'react-jsx',
          strict: true,
          skipLibCheck: true,
          resolveJsonModule: true,
          noEmit: true,
        },
        include: ['src', 'app.manifest.json'],
      },
      null,
      2,
    ) + '\n'
  )
}

function envExample(): string {
  return `# .env.example — copy this file to .env.local and fill in real values.
# .env.local is git-ignored (see .gitignore); NEVER commit real keys.

# --- Runtime (client-side) -------------------------------------------------
# Bundled into the browser by Vite. The VITE_ prefix is what exposes them to
# client code, so only public/anon values belong here. From your Supabase
# project: Dashboard → Project Settings → API.
VITE_SUPABASE_URL=
VITE_SUPABASE_ANON_KEY=

# --- Tooling (used by \`fayz db apply\`) -------------------------------------
# NOT exposed to the browser. Keep the REAL values in .env.local (git-ignored).
# SUPABASE_PROJECT_REF — your project ref (alias: SUPABASE_REF).
#   Dashboard → Project Settings → General.
SUPABASE_PROJECT_REF=
# SUPABASE_PAT — a personal access token (alias: SUPABASE_ACCESS_TOKEN).
#   Dashboard → Account → Access Tokens.
SUPABASE_PAT=
`
}

function agentsMd(name: string, kind: Kind): string {
  return `# AGENTS.md — ${name}

Guidance for AI coding agents (and humans) working in this Fayz ${kind} app.

This app renders from \`app.manifest.json\` through the Fayz app-runtime (consumed
via the public \`@fayz-ai/sdk\` package). Most personalization is manifest edits,
not new code.

## Layout
- \`app.manifest.json\` — app config: surfaces, theme, locale, and \`backend.provider\`.
- \`src/plugins.generated.ts\` — maps manifest plugin ids → platform-bundled factories (generated).
- \`src/registry.tsx\` — app-local custom blocks/pages/components (customization ladder levels 5–7).
- \`.env.example\` — copy to \`.env.local\` and fill in Supabase values (see below).

## Personalization checklist
- Rename / retheme: edit \`name\`, \`theme\`, and the surface \`options\` in \`app.manifest.json\`.
- Content: edit the surface \`options\` (home sections, footer, announcement, etc.).
- Custom code: register blocks/components in \`src/registry.tsx\`, then reference them
  from \`app.manifest.json\` by their \`custom:\` id.

## Connecting a real Supabase
The scaffold ships with \`backend.provider: "mock"\` so it runs with zero setup. To
point it at a real Supabase project:

1. Create a Supabase project — https://supabase.com/dashboard.
2. Copy \`.env.example\` to \`.env.local\` and fill in the values:
   - \`VITE_SUPABASE_URL\` / \`VITE_SUPABASE_ANON_KEY\` — runtime (Project Settings → API).
   - \`SUPABASE_PROJECT_REF\` / \`SUPABASE_PAT\` — tooling for \`fayz db apply\`. Keep these
     in \`.env.local\` (git-ignored); the PAT comes from Account → Access Tokens.
3. Install dependencies: \`npm install\`.
4. Provision the database schema:
   - \`npx fayz db apply --dry-run\`   # preview the ordered migration plan (no network)
   - \`npx fayz db apply\`             # apply it via the Supabase Management API
5. Flip the app to the real backend: in \`app.manifest.json\`, change \`backend.provider\`
   from \`"mock"\` to \`"supabase"\` (add \`"projectRef": "<your-ref>"\` under \`backend\`).
6. Verify: \`npx fayz doctor\`.
`
}

function indexHtml(name: string): string {
  return `<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
}

export function create(kind: string, name: string): number {
  if (!KINDS.includes(kind as Kind)) {
    console.error(`✗ Unknown kind "${kind}". Use: ${KINDS.join(' | ')}`)
    return 1
  }
  if (!name || !/^[a-z0-9][a-z0-9-]*$/.test(name)) {
    console.error(`✗ Provide a kebab-case app name, e.g. fayz create ${kind} my-app`)
    return 1
  }
  const root = resolve(process.cwd(), name)
  if (existsSync(root)) {
    console.error(`✗ Directory "${name}" already exists.`)
    return 1
  }
  const k = kind as Kind
  const template = TEMPLATES[k]

  write(root, 'app.manifest.json', manifestJson(name, k))
  write(root, 'package.json', packageJson(name, k))
  write(root, '.gitignore', 'node_modules\ndist\n.env\n.env.*\n!.env.example\n.DS_Store\n')
  write(root, '.env.example', envExample())
  write(root, 'AGENTS.md', agentsMd(name, k))
  write(root, 'CLAUDE.md', 'See AGENTS.md — the agent guide for this app is agent-agnostic.\n')
  write(root, 'index.html', indexHtml(name))
  write(root, 'vite.config.ts', viteConfig())
  write(root, 'tsconfig.json', tsconfig())
  write(root, 'src/main.tsx', mainTsx(template.surface))
  write(root, 'src/lib/fayz-runtime.ts', fayzRuntimeTs())
  write(root, 'src/plugins.generated.ts', template.pluginsGenerated())
  write(root, 'src/registry.tsx', registryTsx())
  write(root, 'src/styles.css', '/* app-local styles */\n')
  write(
    root,
    'README.md',
    `# ${name}\n\nA Fayz ${k} app. The app uses the public npm \`@fayz-ai/sdk\` package for API/runtime helpers. App runtime, shell, and plugin wiring are platform-bundled until the Beauty manifest proof promotes a public runtime package boundary.\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
  )

  console.log(`✓ Created ${k} app "${name}"`)
  console.log(`\n  cd ${name}`)
  console.log('  npm install')
  console.log('  npm run dev')
  if (template.note) console.log(`\n  Note: ${template.note}`)
  return 0
}
