import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { resolveFayzPackageDependencies, resolveFayzPackageVersion } from '../lib/package-versions.js'

type Kind = 'storefront' | 'admin' | 'member'

const KINDS: Kind[] = ['storefront', 'admin', 'member']

function write(root: string, rel: string, content: string): void {
  const full = resolve(root, rel)
  mkdirSync(dirname(full), { recursive: true })
  writeFileSync(full, content)
}

const RUNTIME_VERSION = resolveFayzPackageVersion('@fayz-ai/runtime')

// ---------------------------------------------------------------------------
// Per-kind template descriptor — the single source the generators read so a new
// surface type is one table entry, not a fork of every function.
// ---------------------------------------------------------------------------
interface KindTemplate {
  /** Extra runtime-versioned deps beyond @fayz-ai/runtime + react. */
  extraDeps: string[]
  manifest(name: string): unknown
  /** Body of src/plugins.generated.ts. */
  pluginsGenerated(): string
  /** Surface name to mount (renderApp surface). */
  surface: string
  note?: string
}

const TEMPLATES: Record<Kind, KindTemplate> = {
  storefront: {
    extraDeps: [],
    surface: 'storefront',
    manifest: (name) => ({
      manifestVersion: 2,
      id: name,
      name,
      backend: { provider: 'mock' },
      locale: { default: 'pt-BR', supported: ['pt-BR'], currency: 'BRL' },
      theme: { name: 'default' },
      surfaces: {
        storefront: {
          scaffold: 'storefront',
          options: {
            announcement: `BEM-VINDO À ${name.toUpperCase()}`,
            home: {
              sections: [
                { type: 'hero', variant: 'banner', slides: [{ title: name, subtitle: 'Sua nova loja' }] },
                { type: 'products', title: 'Destaques', filter: 'all', limit: 8 },
                { type: 'newsletter', title: 'Novidades no seu e-mail' },
              ],
            },
            footer: { about: `${name} — feito com Fayz.` },
          },
        },
      },
    }),
    pluginsGenerated: () =>
      `// Generated by 'fayz create'. Maps manifest plugin ids → installed @fayz/plugin-* factories.
// This storefront app uses no plugins.
export {}
`,
  },

  admin: {
    extraDeps: ['@fayz/plugin-dashboard'],
    surface: 'admin',
    manifest: (name) => ({
      manifestVersion: 2,
      id: name,
      name,
      backend: { provider: 'mock' },
      locale: { default: 'pt-BR', supported: ['pt-BR', 'en'], currency: 'BRL' },
      theme: { brand: 'violet' },
      surfaces: {
        admin: { scaffold: 'admin', plugins: [{ id: 'dashboard' }], pages: [] },
      },
    }),
    pluginsGenerated: () =>
      `// Generated by 'fayz create'. Maps manifest plugin ids → installed @fayz/plugin-* factories.
import { registerPluginFactory } from '@fayz-ai/runtime'
import { createDashboardPlugin } from '@fayz/plugin-dashboard'

registerPluginFactory('dashboard', createDashboardPlugin as never)
`,
  },

  member: {
    // The member scaffold + courses domain are à-la-carte (not in the umbrella).
    extraDeps: ['@fayz/portal', '@fayz/courses'],
    surface: 'member',
    manifest: (name) => ({
      manifestVersion: 2,
      id: name,
      name,
      backend: { provider: 'mock' },
      locale: { default: 'pt-BR', supported: ['pt-BR', 'en'] },
      surfaces: {
        member: {
          scaffold: 'member',
          options: { accent: '#10b981', autoEnroll: true },
        },
      },
    }),
    pluginsGenerated: () =>
      `// Generated by 'fayz create'. Registers the member scaffold + seeds the mock
// courses catalog. Importing @fayz/portal self-registers the 'member' scaffold.
import '@fayz/portal'
import { setCoursesProvider, createMockCoursesProvider } from '@fayz/courses'

setCoursesProvider(createMockCoursesProvider())
`,
    note: 'The member portal seeds a mock course catalog; any login grants access (autoEnroll). Replace the provider with a Supabase-backed one for production.',
  },
}

function packageJson(name: string, kind: Kind): string {
  const deps: Record<string, string> = {
    ...resolveFayzPackageDependencies('stable'),
    react: '^18.3.0',
    'react-dom': '^18.3.0',
  }
  for (const dep of TEMPLATES[kind].extraDeps) deps[dep] = RUNTIME_VERSION
  return (
    JSON.stringify(
      {
        name,
        private: true,
        version: '0.1.0',
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview', doctor: 'fayz doctor' },
        dependencies: deps,
        devDependencies: {
          '@fayz/cli': RUNTIME_VERSION,
          '@vitejs/plugin-react': '^4.3.0',
          typescript: '^5.5.0',
          vite: '^5.4.0',
        },
      },
      null,
      2,
    ) + '\n'
  )
}

function manifestJson(name: string, kind: Kind): string {
  return JSON.stringify(TEMPLATES[kind].manifest(name), null, 2) + '\n'
}

function mainTsx(surface: string): string {
  return `import React from 'react'
import { createRoot } from 'react-dom/client'
import { renderApp } from '@fayz-ai/runtime'
import '@fayz-ai/runtime/styles.css'
import './styles.css'
import './plugins.generated' // registers plugin factories + scaffolds + providers
import './registry' // app-local custom blocks / components / overrides
import manifest from '../app.manifest.json'

createRoot(document.getElementById('root')!).render(
  <React.StrictMode>{renderApp(manifest as never, { surface: '${surface}' })}</React.StrictMode>,
)
`
}

function registryTsx(): string {
  return `// App-local custom code (customization ladder levels 5–7). Register custom
// blocks, pages, components and metric overrides here; reference them from
// app.manifest.json by their 'custom:' id.
//
//   import { registerBlock } from '@fayz-ai/runtime'
//   registerBlock('custom:my-block', MyBlock)
export {}
`
}

function viteConfig(): string {
  return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  // Generated apps consume published @fayz/* packages — no source aliases.
})
`
}

function tsconfig(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          lib: ['ES2020', 'DOM', 'DOM.Iterable'],
          module: 'ESNext',
          moduleResolution: 'bundler',
          jsx: 'react-jsx',
          strict: true,
          skipLibCheck: true,
          resolveJsonModule: true,
          noEmit: true,
        },
        include: ['src', 'app.manifest.json'],
      },
      null,
      2,
    ) + '\n'
  )
}

function indexHtml(name: string): string {
  return `<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
}

export function create(kind: string, name: string): number {
  if (!KINDS.includes(kind as Kind)) {
    console.error(`✗ Unknown kind "${kind}". Use: ${KINDS.join(' | ')}`)
    return 1
  }
  if (!name || !/^[a-z0-9][a-z0-9-]*$/.test(name)) {
    console.error(`✗ Provide a kebab-case app name, e.g. fayz create ${kind} my-app`)
    return 1
  }
  const root = resolve(process.cwd(), name)
  if (existsSync(root)) {
    console.error(`✗ Directory "${name}" already exists.`)
    return 1
  }
  const k = kind as Kind
  const template = TEMPLATES[k]

  write(root, 'app.manifest.json', manifestJson(name, k))
  write(root, 'package.json', packageJson(name, k))
  write(root, '.gitignore', 'node_modules\ndist\n.env\n.env.*\n!.env.example\n.DS_Store\n')
  write(root, 'index.html', indexHtml(name))
  write(root, 'vite.config.ts', viteConfig())
  write(root, 'tsconfig.json', tsconfig())
  write(root, 'src/main.tsx', mainTsx(template.surface))
  write(root, 'src/plugins.generated.ts', template.pluginsGenerated())
  write(root, 'src/registry.tsx', registryTsx())
  write(root, 'src/styles.css', '/* app-local styles */\n')
  write(
    root,
    'README.md',
    `# ${name}\n\nA Fayz ${k} app. The app uses the public npm \`@fayz-ai/sdk\` package for API/runtime helpers, \`@fayz-ai/runtime\` for manifest rendering, and keeps custom code in \`src/registry.tsx\`.\n\n\`\`\`bash\nnpm install\nnpm run dev\nnpm run doctor\n\`\`\`\n`,
  )

  console.log(`✓ Created ${k} app "${name}"`)
  console.log(`\n  cd ${name}`)
  console.log('  npm install')
  console.log('  npm run dev')
  if (template.note) console.log(`\n  Note: ${template.note}`)
  return 0
}
