import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

type Kind = 'storefront' | 'admin'

function write(root: string, rel: string, content: string): void {
  const full = resolve(root, rel)
  mkdirSync(dirname(full), { recursive: true })
  writeFileSync(full, content)
}

const RUNTIME_VERSION = '^0.1.0'

function packageJson(name: string, kind: Kind): string {
  const deps: Record<string, string> = {
    '@fayz/runtime': RUNTIME_VERSION,
    react: '^18.3.0',
    'react-dom': '^18.3.0',
  }
  if (kind === 'admin') {
    deps['@fayz/plugin-dashboard'] = RUNTIME_VERSION
  }
  return (
    JSON.stringify(
      {
        name,
        private: true,
        version: '0.1.0',
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview', doctor: 'fayz doctor' },
        dependencies: deps,
        devDependencies: {
          '@fayz/cli': RUNTIME_VERSION,
          '@vitejs/plugin-react': '^4.3.0',
          typescript: '^5.5.0',
          vite: '^5.4.0',
        },
      },
      null,
      2,
    ) + '\n'
  )
}

function storefrontManifest(name: string): string {
  return (
    JSON.stringify(
      {
        manifestVersion: 2,
        id: name,
        name,
        backend: { provider: 'mock' },
        locale: { default: 'pt-BR', supported: ['pt-BR'], currency: 'BRL' },
        theme: { name: 'default' },
        surfaces: {
          storefront: {
            scaffold: 'storefront',
            options: {
              announcement: `BEM-VINDO À ${name.toUpperCase()}`,
              home: {
                sections: [
                  { type: 'hero', variant: 'banner', slides: [{ title: name, subtitle: 'Sua nova loja' }] },
                  { type: 'products', title: 'Destaques', filter: 'all', limit: 8 },
                  { type: 'newsletter', title: 'Novidades no seu e-mail' },
                ],
              },
              footer: { about: `${name} — feito com Fayz.` },
            },
          },
        },
      },
      null,
      2,
    ) + '\n'
  )
}

function adminManifest(name: string): string {
  return (
    JSON.stringify(
      {
        manifestVersion: 2,
        id: name,
        name,
        backend: { provider: 'mock' },
        locale: { default: 'pt-BR', supported: ['pt-BR', 'en'], currency: 'BRL' },
        theme: { brand: 'violet' },
        surfaces: {
          admin: {
            scaffold: 'admin',
            plugins: [{ id: 'dashboard' }],
            pages: [],
          },
        },
      },
      null,
      2,
    ) + '\n'
  )
}

function mainTsx(): string {
  return `import React from 'react'
import { createRoot } from 'react-dom/client'
import { renderApp } from '@fayz/runtime'
import '@fayz/runtime/styles.css'
import './styles.css'
import './plugins.generated' // registers plugin factories + scaffolds
import './registry' // app-local custom blocks / components / overrides
import manifest from '../app.manifest.json'

createRoot(document.getElementById('root')!).render(
  <React.StrictMode>{renderApp(manifest as never)}</React.StrictMode>,
)
`
}

function pluginsGenerated(kind: Kind): string {
  if (kind !== 'admin') {
    return `// Generated by 'fayz create'. Maps manifest plugin ids → installed @fayz/plugin-* factories.
// Regenerated by the platform when the manifest's plugin set changes.
// This storefront app uses no plugins.
export {}
`
  }
  return `// Generated by 'fayz create'. Maps manifest plugin ids → installed @fayz/plugin-* factories.
import { registerPluginFactory } from '@fayz/runtime'
import { createDashboardPlugin } from '@fayz/plugin-dashboard'

registerPluginFactory('dashboard', createDashboardPlugin as never)
`
}

function registryTsx(): string {
  return `// App-local custom code (customization ladder levels 5–7). Register custom
// blocks, pages, components and metric overrides here; reference them from
// app.manifest.json by their 'custom:' id.
//
//   import { registerBlock } from '@fayz/runtime'
//   registerBlock('custom:my-block', MyBlock)
export {}
`
}

function viteConfig(): string {
  return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  // Generated apps consume published @fayz/* packages — no source aliases.
})
`
}

function tsconfig(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          lib: ['ES2020', 'DOM', 'DOM.Iterable'],
          module: 'ESNext',
          moduleResolution: 'bundler',
          jsx: 'react-jsx',
          strict: true,
          skipLibCheck: true,
          resolveJsonModule: true,
          noEmit: true,
        },
        include: ['src', 'app.manifest.json'],
      },
      null,
      2,
    ) + '\n'
  )
}

function indexHtml(name: string): string {
  return `<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
}

export function create(kind: string, name: string): number {
  if (kind !== 'storefront' && kind !== 'admin') {
    console.error(`✗ Unknown kind "${kind}". Use: storefront | admin`)
    return 1
  }
  if (!name || !/^[a-z0-9][a-z0-9-]*$/.test(name)) {
    console.error('✗ Provide a kebab-case app name, e.g. fayz create storefront my-shop')
    return 1
  }
  const root = resolve(process.cwd(), name)
  if (existsSync(root)) {
    console.error(`✗ Directory "${name}" already exists.`)
    return 1
  }
  const k = kind as Kind

  write(root, 'app.manifest.json', k === 'admin' ? adminManifest(name) : storefrontManifest(name))
  write(root, 'package.json', packageJson(name, k))
  write(root, '.npmrc', '@fayz:registry=https://npm.pkg.github.com\n')
  write(root, '.gitignore', 'node_modules\ndist\n.env\n.env.*\n!.env.example\n.DS_Store\n')
  write(root, 'index.html', indexHtml(name))
  write(root, 'vite.config.ts', viteConfig())
  write(root, 'tsconfig.json', tsconfig())
  write(root, 'src/main.tsx', mainTsx())
  write(root, 'src/plugins.generated.ts', pluginsGenerated(k))
  write(root, 'src/registry.tsx', registryTsx())
  write(root, 'src/styles.css', '/* app-local styles */\n')
  write(
    root,
    'README.md',
    `# ${name}\n\nA Fayz ${k} app. The app is defined by \`app.manifest.json\`; custom code lives in \`src/registry.tsx\`.\n\n\`\`\`bash\nnpm install\nnpm run dev\nnpm run doctor\n\`\`\`\n`,
  )

  console.log(`✓ Created ${k} app "${name}"`)
  console.log(`\n  cd ${name}`)
  console.log('  npm install   # needs GitHub Packages auth (NODE_AUTH_TOKEN) for @fayz/*')
  console.log('  npm run dev')
  if (k === 'admin') {
    console.log(
      '\n  Note: the admin scaffold ships with the saas-core de-bridge (W6); storefront apps render today.',
    )
  }
  return 0
}
