// Files every generated app shares, regardless of surface kind. The shapes are
// copied from the dogfood apps (pulse-store / beauty-saas / course-members) —
// they are the proven "compiles against published npm" baseline.

export type Kind = 'storefront' | 'admin' | 'member'

export interface AppTemplate {
  kind: Kind
  /** Dev/preview port, matching the dogfood port lanes. */
  port: number
  /** @fayz-ai packages — versions resolved from the release channel. */
  fayzDependencies: string[]
  /** Non-fayz runtime deps with their pinned ranges. */
  externalDependencies: Record<string, string>
  files(name: string): Record<string, string>
  /** Kind-specific personalization checklist, embedded in CLAUDE.md. */
  checklist: string
  note?: string
}

/** kebab-case app name → display title ("minha-loja" → "Minha Loja"). */
export function titleCase(name: string): string {
  return name
    .split('-')
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(' ')
}

// lucide-react must stay on the SDK's own range (^0.400) — a second major in
// the app graph doubles Vite optimizeDeps work and bloats the preview RAM.
export const SHARED_EXTERNAL_DEPS: Record<string, string> = {
  react: '^18.3.0',
  'react-dom': '^18.3.0',
  zustand: '^4.5.0',
  'lucide-react': '^0.400.0',
}

export const SHARED_DEV_DEPS: Record<string, string> = {
  '@types/node': '^20.0.0',
  '@types/react': '^18.3.0',
  '@types/react-dom': '^18.3.0',
  '@vitejs/plugin-react': '^4.3.0',
  autoprefixer: '^10.4.0',
  postcss: '^8.4.0',
  tailwindcss: '^3.4.0',
  typescript: '^5.5.0',
  vite: '^5.4.0',
}

export function viteConfig(port: number): string {
  return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { fayzVite } from '@fayz-ai/sdk/vite'

// fayzVite resolves @fayz-ai/* from local SDK source when the fayz-sdk repo is
// checked out two levels up; everywhere else (including this app's default
// location) it falls back to the published npm packages in node_modules.
export default defineConfig(fayzVite({ port: ${port}, plugins: [react()] }))
`
}

export function tsconfig(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          lib: ['ES2022', 'DOM', 'DOM.Iterable'],
          jsx: 'react-jsx',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
        },
        include: ['src', 'app.manifest.json', 'vite.config.ts', 'tailwind.config.ts'],
      },
      null,
      2,
    ) + '\n'
  )
}

export function postcssConfig(): string {
  return `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`
}

export function tailwindConfig(): string {
  return `import { fayzTailwind } from '@fayz-ai/ui/tailwind'

export default fayzTailwind()
`
}

export function stylesCss(): string {
  return `@import '@fayz-ai/ui/styles.css';
`
}

export function indexHtml(title: string): string {
  return `<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="data:," />
    <title>${title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
}

export function gitignore(): string {
  return 'node_modules\ndist\n.env\n.env.*\n!.env.example\n.DS_Store\n'
}

export function mainTsx(opts?: { beforeRender?: string }): string {
  return `import React from 'react'
import ReactDOM from 'react-dom/client'
import './plugins.generated' // plugin/scaffold/provider wiring (AI-BUILDER contract file)
import './registry' // app-local custom blocks / components / overrides
import { App } from './App'
import './styles.css'
${opts?.beforeRender ?? ''}
ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`
}

export function registryTsx(): string {
  return `// App-local custom code (customization ladder levels 5-7). Register custom
// blocks, pages, components and metric overrides here and reference them from
// the config by id, e.g.:
//
//   import { registerComponent } from '@fayz-ai/core'
//   registerComponent('custom:my-block', MyBlock)
export {}
`
}

export function readme(name: string, kind: Kind): string {
  return `# ${titleCase(name)}

A Fayz ${kind} app generated by \`fayz create\`. \`src/config/app.ts(x)\` is the
source of truth; \`app.manifest.json\` is a derived index of it (keep both in
sync). See CLAUDE.md for the working rules.

\`\`\`bash
npm install
npm run dev
\`\`\`
`
}

const CONTRACT_RULES = `## Contract rules (do not break)

- **Source of truth**: \`src/config/app.ts(x)\`. \`app.manifest.json\` is a DERIVED
  index of that config — after every config change, update the manifest to match
  (id, name, backend, locale, theme, surfaces/plugins). A stale manifest makes
  the platform Panel lie.
- **Boundary**: never import provider SDKs directly (\`@supabase/supabase-js\`,
  \`stripe\`, \`mercadopago\`, \`googleapis\`, ...). Go through the Fayz seams
  (\`getSupabaseClientOptional\` etc. from \`@fayz-ai/core\`). \`fayz doctor\` checks this.
- **Dependencies**: only \`@fayz-ai/*\` packages listed in the SDK's
  supported-surface plus ordinary UI libs. No new backend/provider deps.
- **Custom code** goes in \`src/registry.tsx\` (or \`src/plugins/<name>/\` for an
  app-local plugin via \`fayz create plugin <name>\`), never in SDK internals.

## Verification gate (run before calling any change done)

1. \`npm run build\` — must pass.
2. \`fayz doctor .\` (or \`npx --yes @fayz-ai/cli doctor .\`) — never finish red.
3. \`npm run dev\` in background → open the app (or curl the URL and grep the app
   name) → confirm the surface renders → kill the server.`

export function claudeMd(name: string, kind: Kind, checklist: string): string {
  return `# ${titleCase(name)} — Fayz ${kind} app

Generated by \`fayz create ${kind} ${name}\`. Runs on mock data providers out of
the box (no backend/env needed); \`npm run dev\` and it renders.

## Commands
- \`npm run dev\` — dev server
- \`npm run build\` — typecheck + production build
- \`npm run preview\` — serve the production build

${CONTRACT_RULES}

## Personalization checklist (${kind})

${checklist}
`
}
