// Single source of truth for e2e selectors. Components import from here;
// Playwright specs assert against the same constants — they cannot drift.
export const TID = {
  // header
  headerSearch: 'header-search',
  cartButton: 'cart-button',
  cartCount: 'cart-count',
  accountLink: 'account-link',
  accountDropdown: 'account-dropdown',
  announcementBar: 'announcement-bar',
  navLink: (label: string) => `nav-${label.toLowerCase().replace(/\s+/g, '-')}`,
  navCategory: (slug: string) => `nav-cat-${slug}`,
  accountName: 'account-name',
  // home sections
  hero: 'home-hero',
  heroPrev: 'hero-prev',
  heroNext: 'hero-next',
  mediaCarousel: 'media-carousel',
  mediaCarouselPrev: 'media-carousel-prev',
  mediaCarouselNext: 'media-carousel-next',
  productSlider: 'product-slider',
  productSliderViewport: 'product-slider-viewport',
  productSliderPrev: 'product-slider-prev',
  productSliderNext: 'product-slider-next',
  categoryShowcase: 'category-showcase',
  productRail: 'product-rail',
  benefits: 'benefits-row',
  promoBanner: 'promo-banner',
  manifesto: 'manifesto',
  testimonials: 'testimonials',
  newsletter: 'newsletter',
  newsletterEmail: 'newsletter-email',
  newsletterSubmit: 'newsletter-submit',
  newsletterDone: 'newsletter-done',
  // catalog
  productGrid: 'product-grid',
  productCard: 'product-card',
  productCardName: 'product-card-name',
  productCardPrice: 'product-card-price',
  productCardAdd: 'product-card-add',
  badgeSale: 'badge-sale',
  badgeSoldout: 'badge-soldout',
  // filters
  filterCategory: (slug: string) => `filter-category-${slug}`,
  filterPriceMin: 'filter-price-min',
  filterPriceMax: 'filter-price-max',
  filterInstock: 'filter-instock',
  sortSelect: 'sort-select',
  filtersClear: 'filters-clear',
  // product detail
  pdpName: 'pdp-name',
  pdpPrice: 'pdp-price',
  pdpComparePrice: 'pdp-compare-price',
  pdpDescription: 'pdp-description',
  productOptionGroup: (id: string) => `product-option-${id.toLowerCase().replace(/\s+/g, '-')}`,
  productOptionValue: (id: string, value: string) => `product-option-${id.toLowerCase().replace(/\s+/g, '-')}-${value.toLowerCase().replace(/\s+/g, '-')}`,
  pdpQtyInput: 'pdp-qty-input',
  pdpAddToCart: 'pdp-add-to-cart',
  pdpRoot: 'pdp-root',
  pdpGallery: 'pdp-gallery',
  pdpActions: 'pdp-actions',
  pdpEnquiryButton: 'pdp-enquiry-button',
  enquiryForm: 'enquiry-form',
  enquiryName: 'enquiry-name',
  enquiryEmail: 'enquiry-email',
  enquiryPhone: 'enquiry-phone',
  enquirySubject: 'enquiry-subject',
  enquiryMessage: 'enquiry-message',
  enquirySubmit: 'enquiry-submit',
  enquirySuccess: 'enquiry-success',
  enquiryError: 'enquiry-error',
  // cart
  cartDrawer: 'cart-drawer',
  cartLine: 'cart-line',
  lineQty: 'line-qty',
  lineInc: 'line-inc',
  lineDec: 'line-dec',
  lineRemove: 'line-remove',
  cartSubtotal: 'cart-subtotal',
  discountInput: 'discount-input',
  discountApply: 'discount-apply',
  discountRow: 'discount-row',
  discountError: 'discount-error',
  cartShipping: 'cart-shipping',
  shippingProgress: 'shipping-progress',
  cartTotal: 'cart-total',
  goCheckout: 'go-checkout',
  cartEmpty: 'cart-empty',
  // checkout
  checkoutEmail: 'checkout-email',
  checkoutName: 'checkout-name',
  checkoutStreet: 'checkout-street',
  checkoutCity: 'checkout-city',
  checkoutZip: 'checkout-zip',
  checkoutCard: 'checkout-card',
  checkoutExpiry: 'checkout-expiry',
  checkoutCvc: 'checkout-cvc',
  placeOrder: 'place-order',
  checkoutError: 'checkout-error',
  checkoutProcessing: 'checkout-processing',
  // confirmation
  orderNumber: 'order-number',
  orderStatus: 'order-status',
  orderTracking: 'order-tracking',
  orderTrackingStep: (step: string) => `order-tracking-step-${step}`,
  orderTotal: 'order-total',
  viewPurchases: 'view-purchases',
  // account
  customerAccountShell: 'customer-account-shell',
  customerAccountMenu: 'customer-account-menu',
  orderDetail: 'order-detail',
  authTabSignin: 'auth-tab-signin',
  authTabSignup: 'auth-tab-signup',
  signinEmail: 'signin-email',
  signinPassword: 'signin-password',
  signinName: 'signin-name',
  signinSubmit: 'signin-submit',
  authError: 'auth-error',
  purchasesList: 'purchases-list',
  purchaseItem: 'purchase-item',
  purchasesEmpty: 'purchases-empty',
  signout: 'signout',
} as const
